CV/CV/Controllers/CVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class CVController : Controller
    {
        // GET: CV
        public ActionResult Home()
        {
            return View();
        }
        public ActionResult Education()
        {
            return View();
        }
        public ActionResult Projects()
        {
            return View();
        }
        public ActionResult References()
        {
            return View();
        }
    }
}

CV/CV/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CV.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CV/CV/Views/CV/Education.cshtml
@{
    ViewBag.Title = "Education";
}

<h2>Education</h2>

<table style="width:50%">
    <tr>
        <th>Examination</th>
        <th>Institute</th>
        <th>Result</th>
    </tr>
    <tr>
        <td>SSC</td>
        <td>Rajshahi Cantonment Board High School</td>
        <td>GPA 5</td>
    </tr>
    <tr>
        <td>HSC</td>
        <td>New Government Degree College</td>
        <td>GPA 5</td>
    </tr>
</table>

CV/CV/Views/CV/Home.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Home</h2>
<h3>Name: Mahfuza Sharmili Jui</h3>
<h3>ID: 19-39398-1</h3>

CV/CV/Views/CV/Projects.cshtml
@{
    ViewBag.Title = "Projects";
}

<h2>Projects</h2>


<table style="width:50%">
    <tr>
        <th>Course</th>
        <th>Project Name</th>
    </tr>
    <tr>
        <td>Database</td>
        <td>Coffee Shop Management System</td>
    </tr>
    <tr>
        <td>OOAD</td>
        <td>E-Commerce site Management System</td>
    </tr>
    <tr>
        <td>Java</td>
        <td>Scientific Calculator</td>
    </tr>
    <tr>
        <td>C#</td>
        <td>Housing Management System for AIUB students</td>
    </tr>
    <tr>
        <td>Software Engineering</td>
        <td>Housing Management System for AIUB students</td>
    </tr>
    <tr>
        <td>Web Technology</td>
        <td>Housing Management System for AIUB students</td>
    </tr>
</table>

CV/CV/Views/CV/References.cshtml
@{
    ViewBag.Title = "References";
}

<h2>References</h2>

<h3>TANVIR AHMED</h3>

CV/CV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Home", "CV")</li>
                    <li>@Html.ActionLink("Education", "Education", "CV")</li>
                    <li>@Html.ActionLink("Projects", "Projects", "CV")</li>
                    <li>@Html.ActionLink("References", "References", "CV")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>